server:
  port: 3366



spring:
  application:
    name: config-client3366  #名字一般不要改变 就是注册中心的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root



mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zwq.springcloud.entity    # 所有Entity别名类所在包
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true  #是否从EurekaServer抓取已有的注册信息, 默认为true,单节点无所谓
    #集群必须设置为true 才能配置Ribbon使用负载均衡
    service-url:
      #单机
      defaultZone: http://eureka7001.com:7001/eureka
      #集群
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  

